?start : value+

?value : exp

?exp:  atom | list |qt

?number : INT | FLOAT

?atom : (STRING | number | SYMBOL | BOOL | operator) ->atom

?list : "(" exp* ")" ->list

?operator : /[\+|-|\/|\*]/

?qt : ("'"exp*) ->quote

// Terminais
SYMBOL.0  : /[-!+\/*@$%^&~<>?|\\\w=]+/
STRING    : /"[^"\\]*(\\[^\n\t\r\f][^"\\]*)*"/
INT.1     : /-?\d+/
FLOAT.2   : /-?\d+\.\d+/
BOOL : /#t/|/#f/

%ignore /\s+/
%ignore /;[^\n]*/